/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackEdit: typeof import('./src/components/backEdit.vue')['default']
    ChartOutline: typeof import('./src/components/ChartOutline.vue')['default']
    EditForm: typeof import('./src/components/EditForm.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FourPage: typeof import('./src/components/FourPage.vue')['default']
    LeftMenu: typeof import('./src/components/LeftMenu.vue')['default']
    OnePage: typeof import('./src/components/OnePage.vue')['default']
    REditForm: typeof import('./src/components/rEditForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThreePage: typeof import('./src/components/ThreePage.vue')['default']
    TopMenu: typeof import('./src/components/TopMenu.vue')['default']
    TwiceElDialog: typeof import('./src/components/TwiceElDialog.vue')['default']
    TwiceElForm: typeof import('./src/components/TwiceElForm.vue')['default']
    TwiceElPagination: typeof import('./src/components/TwiceElPagination.vue')['default']
    TwiceElTable: typeof import('./src/components/TwiceElTable.vue')['default']
    TwoPage: typeof import('./src/components/TwoPage.vue')['default']
  }
}
